model:
  # paths
  llama_path: "meta-llama/Llama-3.2-3B-Instruct"
  whisper_path: "openai/whisper-large-v2"
  beats_path: "/root/base_data/checkpoints/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2.pt"

  token: "<hf_token>" # Use hf token to access gated repositories

  ckpt: "" #"model ckpt" # if not "", load model from ckpt for training or evaluation

  freeze_whisper: True
  freeze_beats: True

  # window-level Q-Former
  use_speech_Qformer: True
  freeze_speech_QFormer: False
  window_level_Qformer: True
  num_speech_query_token: 1
  second_per_window: 0.333333
  second_stride: 0.333333

  speech_llama_proj_model: ""
  freeze_speech_llama_proj: False

  # LoRA
  lora: True
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.1

  multi_prompt: True
  prompt_template: "USER: {}\nASSISTANT:"
  prompt_path: "prompts/train_prompt.json"
  test_prompt_path: "prompts/test_prompt.json"
  max_txt_len: 300
  end_sym: "<|end_of_text|>" # TODO: change eos token

datasets:
  prefix: "/data/home/audiolm-evaluator/audiolm-trainer"
  train_ann_path: "data/train_stage1_1b.json"
  valid_ann_path: "data/val_stage1_1b.json"
  whisper_path: "openai/whisper-large-v2"

run:
  # log & settings
  seed: 42
  output_dir: "outputs_stage1_only"
  evaluate: False # if True, only evaluate model on test data
  exp_name: "llama-3.2-3B-speech-embeds"

  log_freq: 5
  epoch_based: False
  iters_per_epoch: 3000
  accum_grad_iters: 1
  batch_size_train: 8
  batch_size_eval: 8
  num_workers: 8

  device: "cuda"
  use_distributed: True
  amp: True
  world_size: 2
  dist_url: "env://"

  # optimizer & scheduler
  optims:
    max_epoch: 30
    warmup_steps: 3000
    warmup_start_lr: 1e-6
    init_lr: 3e-5
    min_lr: 1e-5
    weight_decay: 0.05
    beta2: 0.999
